### PR TITLE
Updating golang to 1.18 and dependencies to latest versions

### PR DESCRIPTION
**Pull request by Red-GV**

### CODE REVIEW

**Comment by periklis** [comment]
@Red-GV We can certainly remove vendoring from this project and benefit having readable PRs

**Comment by Red-GV** [comment]
@periklis I will make a following PR to update `ginkgo` to v2. The new updates seem to help with the data formatting. 

I also removed the `gnuplot` from the CircleCi tests. The update triggers a restart which stalls the entire test.

**Comment by periklis** [comment]
> @periklis I will make a following PR to update `ginkgo` to v2. The new updates seem to help with the data formatting.
> 
> I also removed the `gnuplot` from the CircleCi tests. The update triggers a restart which stalls the entire test.

I don't believe we are compatible with gingko v2 because it remove the Benchmarker IIRC.

**Comment by Red-GV** [comment]
@periklis It mainly removes the custom reporters. The `benchmarker` is replaces with `experiment`, which essentially does the same job. 

I did a bare minimum conversion yesterday and the changes also include parsing out the output data as a JSON file now as well. Potentially this may give us a better file format to use than writing all the data down ourselves.

**Review by periklis — APPROVED** [review]

**Pull request merged**
