### PR TITLE
Update ginkgo to v2 

### PR DESCRIPTION
**Pull request by Red-GV**
This PR updates ginkgo to v2. This is a major change in the library that comes with many improvements to performance.

Among the changes is the removal of the custom reporters, which we were using to report the values. However, v2 does print the data into the JSON or XML file for us. Overall, I think the update does also give us better code readability on the go side of things as the formatting of the reports can be confusing at first.

I'm going to put this into draft mode for now while I try to figure out how to see all of the `N` sampled values if we care to keep that on a graph as previously. If we decide to not to, we get the tables in the files with the values of the experiment. 

Attached is currently what they look like.

Screen Shot 2022-09-13 at 3 38 27 PM

cc: @eranra

### CODE REVIEW

**Review by periklis — COMMENTED** [review]
Looks awesome and cleans up a bit of the mess to have N replicas of a benchmark. I like the new samping configuration API.

**Comment by periklis** [comment]
> Among the changes is the removal of the custom reporters, which we were using to report the values. However, v2 does print the data into the JSON or XML file for us. Overall, I think the update does also give us better code readability on the go side of things as the formatting of the reports can be confusing at first.
> 
> I'm going to put this into draft mode for now while I try to figure out how to see all of the `N` sampled values if we care to keep that on a graph as previously. If we decide to not to, we get the tables in the files with the values of the experiment.
> 

FYI custom reporters were initially a workaround for visualizing the data. As the original author I never intended to support automatic visualization (e.g. via gnuplot) from this tool long term. Thus custom reporters were more a short cut rather the final goal. AFAIU ginkgo v2 presents the raw data in a _stable_ format in json. If they suggest any tooling for visualizing these raw data I am fine with finishing and merging this PR as is. We can add scripts to transform the json output to a report with graphs in a separate PR.

**Comment by Red-GV** [comment]
@periklis I was mistaken while doing my testing. All the recorded values are there. I was expecting 10 when I was only running 2 samples. 

In short, yes. The JSON files contains all the data from the benchmark tests. We can look into the JSON to either have the table (which is the screenshot above) or the JSON representation, which we can open to look at all the values and then render into a graph if we so wish.

I agree that we should mark this move as complete for now and consider making the graphs a separate topic. They don't - as far as I know - don't mention any specific or recommended visualization tools.

**Review by periklis — COMMENTED** [review]
:rocket:

**Comment by periklis** [comment]
> @periklis I was mistaken while doing my testing. All the recorded values are there. I was expecting 10 when I was only running 2 samples.
> 
> In short, yes. The JSON files contains all the data from the benchmark tests. We can look into the JSON to either have the table (which is the screenshot above) or the JSON representation, which we can open to look at all the values and then render into a graph if we so wish.
> 

IMHO we wish to have at least a `make report` command using (if possible vendored) cli tools to compile a nice report from JSON. Can you spent some time on researching on how to solve this? I agree we can resolve in a separate PR.

> I agree that we should mark this move as complete for now and consider making the graphs a separate topic. They don't - as far as I know - don't mention any specific or recommended visualization tools.

**Review by periklis — COMMENTED** [review]
Looks good to me

**Comment by Red-GV** [comment]
It looks like there's an issue about - maybe - adding an HTML reporter to Ginkgo at some point. It would be possible to take all the tables and place them in one file. 

However, I'm not entirely sure which direction to go about the values for graphing. Perhaps something with Python, but that might require a dependency or two to make into useful.

**Comment by Red-GV** [comment]
@periklis Can we go ahead and merge this one in? I'll pick up the visualization in another PR.

**Review by periklis — APPROVED** [review]

**Pull request merged**
