### PR TITLE
Adding message size flag for logger deployment

### PR DESCRIPTION
**Pull request by Red-GV**

### CODE REVIEW

**Review by periklis — DISMISSED** [review]

**Comment by periklis** [comment]
Before merging this, does this was with a logger image that doesn't provide this flag right now? IC broken tests on the build.

**Comment by Red-GV** [comment]
This won't work with a previous image. `go` tosses this error (`flag provided but not defined`) on the older image.

**Comment by periklis** [comment]
> This won't work with a previous image. `go` tosses this error (`flag provided but not defined`) on the older image.

Let's fix the logger first then ;)

**Comment by Red-GV** [comment]
Oh whoops, forgot to include the PR for the logger. XD
https://github.com/periklis/logger/pull/3

**Review by eranra — APPROVED** [review]

**Comment by Red-GV** [comment]
Closing. Don't expressly need this PR due to #51.

**Pull request closed without merging**
