### PR TITLE
Ocp test conf new logger

### PR DESCRIPTION
**Pull request by eranra**

### CODE REVIEW

**Comment by Red-GV** [comment]
@eranra I took this branch for a spin. The very first read test failed with a "empty query" and then the others seemed to work. Any ideas?

**Comment by eranra** [comment]
@Red-GV I bumped up the amount of writes before trying to query/read and now everything is working

**Comment by eranra** [comment]
@periklis can you please merge?

**Comment by Red-GV** [comment]
Going to close this PR in favor of #54

**Pull request closed without merging**
